services:
  - type: web
    name: http-server
    env: docker
    region: singapore
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.backend.yml
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: Resend_API
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: PUBLIC_URL
        value: https://http-server-6i9s.onrender.com

  - type: web
    name: worker
    env: docker
    region: singapore
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.Queue.yml
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: BACKEND_URL
        value: https://http-server-6i9s.onrender.com
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: https://worker-s4bs.onrender.com

  - type: web
    name: pinging
    env: docker
    region: singapore
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.pinging.yml
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: BACKEND_URL
        value: https://http-server-6i9s.onrender.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: PUBLIC_URL
        value: https://pinging-32id.onrender.com

  - type: web
    name: websocket
    env: docker
    region: singapore
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.websocket.yml
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: PUBLIC_URL
        value: https://websocket-axsc.onrender.com

  - type: redis
    name: redis
    region: singapore
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction