FROM node:22-alpine AS build

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npm install -g pnpm
WORKDIR /app

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml 
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml 
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY packages packages
COPY ./apps/http-server ./apps/http-server

RUN pnpm install --frozen-lockfile

RUN pnpm run db:generate

RUN pnpm --filter http-server... run build

FROM node:22-alpine AS run

WORKDIR /app
RUN npm install -g pnpm

COPY --from=build /app/package.json ./
COPY --from=build /app/pnpm-lock.yaml ./
COPY --from=build /app/pnpm-workspace.yaml ./

COPY --from=build /app/packages/DB ./packages/DB

COPY --from=build /app/packages/typescript-config ./packages/typescript-config
COPY --from=build /app/packages/eslint-config ./packages/eslint-config

COPY --from=build /app/apps/http-server/dist ./apps/http-server/dist
COPY --from=build /app/apps/http-server/package.json ./apps/http-server/package.json

RUN pnpm install --frozen-lockfile
EXPOSE 3001

CMD ["sh", "-c", "pnpm --filter @repo/db exec prisma migrate deploy --schema=./prisma/schema.prisma && pnpm --filter http-server start:prod"]