FROM node:22-alpine AS build

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npm install -g pnpm
WORKDIR /app

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml 
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml 
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY packages packages

COPY ./apps/pinging ./apps/pinging

RUN pnpm install --frozen-lockfile
RUN pnpm run db:generate

RUN pnpm run build --filter pinging...

FROM node:22-alpine AS run

WORKDIR /app
RUN npm install -g pnpm

COPY --from=build /app/package.json ./
COPY --from=build /app/pnpm-lock.yaml ./
COPY --from=build /app/pnpm-workspace.yaml ./

COPY --from=build /app/packages/DB ./packages/DB

COPY --from=build /app/packages/Queue/dist ./packages/Queue/dist
COPY --from=build /app/packages/Queue/package.json ./packages/Queue/package.json

COPY --from=build /app/packages/typescript-config ./packages/typescript-config
COPY --from=build /app/packages/eslint-config ./packages/eslint-config

COPY --from=build /app/apps/pinging/dist ./apps/pinging/dist
COPY --from=build /app/apps/pinging/package.json ./apps/pinging/package.json

RUN pnpm install --frozen-lockfile
EXPOSE 3002

CMD ["sh", "-c", "DATABASE_URL=$DATABASE_URL pnpm --filter @repo/db exec prisma migrate deploy --schema=./prisma/schema.prisma && pnpm --filter pinging start:prod"]