FROM node:20-alpine AS build

RUN npm install -g pnpm
WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml turbo.json package.json ./

COPY apps/websocket ./apps/websocket

RUN pnpm install --filter websocket --frozen-lockfile

FROM node:20-alpine AS run

WORKDIR /app
RUN npm install -g pnpm

COPY --from=build /app/package.json ./
COPY --from=build /app/pnpm-lock.yaml ./
COPY --from=build /app/pnpm-workspace.yaml ./
COPY --from=build /app/apps/websocket ./apps/websocket

RUN pnpm install --filter websocket --frozen-lockfile --prod

EXPOSE 3003

CMD ["pnpm", "--filter", "websocket", "start"]