FROM node:22-alpine AS build

RUN npm install -g pnpm
WORKDIR /app

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml 
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml 
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY packages packages

RUN pnpm install --frozen-lockfile

RUN pnpm run build --filter @repo/queue...

FROM node:22-alpine AS run

WORKDIR /app
RUN npm install -g pnpm

COPY --from=build /app/package.json ./
COPY --from=build /app/pnpm-lock.yaml ./
COPY --from=build /app/pnpm-workspace.yaml ./

COPY --from=build /app/packages/Queue/dist ./packages/Queue/dist
COPY --from=build /app/packages/Queue/package.json ./packages/Queue/package.json

COPY --from=build /app/packages/DB ./packages/DB

COPY --from=build /app/packages/typescript-config ./packages/typescript-config

RUN pnpm install --frozen-lockfile

CMD ["pnpm", "--filter", "@repo/queue", "run", "worker:prod"]